/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacoffee.view.manage;

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacoffee.bus.NhanVien_BUS;
import javacoffee.pojo.NhanVien_pojo;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kikkdt (KietDt)
 */
public class NhanVienGUI extends javax.swing.JPanel {
    
    private DefaultTableModel dtm;
    private ArrayList<NhanVien_pojo> lstNhanVien = new NhanVien_BUS().getList();
    private static final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public NhanVienGUI() {
        initComponents();
        loadTableNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogNhanVien = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        lblNhanVien = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        radioBtnNam = new javax.swing.JRadioButton();
        radioBtnNu = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlNhanVien = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTongSo = new javax.swing.JLabel();

        dialogNhanVien.setTitle("Quản lý Nhân viên");
        dialogNhanVien.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png"))
        );
        dialogNhanVien.setMinimumSize(new java.awt.Dimension(475, 480));
        dialogNhanVien.setModal(true);
        dialogNhanVien.setResizable(false);
        dialogNhanVien.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogNhanVienWindowClosing(evt);
            }
        });

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 87, 29), 2, true));
        jPanel7.setMaximumSize(new java.awt.Dimension(440, 350));
        jPanel7.setMinimumSize(new java.awt.Dimension(440, 350));
        jPanel7.setPreferredSize(new java.awt.Dimension(440, 350));

        lblNhanVien.setBackground(new java.awt.Color(149, 87, 29));
        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setText("Thêm Nhân viên");
        lblNhanVien.setOpaque(true);

        txtTenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenNV.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenNV.setToolTipText("Nhập tên món ăn/ thức uống");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 56, 19));
        jLabel13.setText("Tên NV:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(96, 56, 19));
        jLabel15.setText("Giới tính:");

        buttonGroup1.add(radioBtnNam);
        radioBtnNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnNam.setText("Nam");
        radioBtnNam.setFocusable(false);

        buttonGroup1.add(radioBtnNu);
        radioBtnNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioBtnNu.setText("Nữ");
        radioBtnNu.setFocusable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 56, 19));
        jLabel16.setLabelFor(dateChooser);
        jLabel16.setText("Ngày vào làm:");

        dateChooser.setDateFormatString("dd/MM/yyyy");
        dateChooser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateChooser.setIcon(new ImageIcon(getClass().getResource("/icons8-calendar-24.png")));
        dateChooser.setMaxSelectableDate(new Date()
        );
        dateChooser.setMinSelectableDate(new java.util.Date(-62135791130000L));
        dateChooser.setMinimumSize(new java.awt.Dimension(35, 35));
        dateChooser.setPreferredSize(new java.awt.Dimension(88, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 56, 19));
        jLabel14.setText("Địa chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setToolTipText("Nhập địa chỉ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(96, 56, 19));
        jLabel17.setText("Số điện thoại:");

        txtSdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSdt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSdt.setToolTipText("Nhập số điện thoại");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(96, 56, 19));
        jLabel18.setLabelFor(txtChucVu);
        jLabel18.setText("Chức vụ:");

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChucVu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtChucVu.setToolTipText("Nhập số điện thoại");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSdt)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(radioBtnNam)
                                .addGap(26, 26, 26)
                                .addComponent(radioBtnNu))
                            .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtChucVu))))
                .addContainerGap())
            .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBtnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnNu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        btnSave.setBackground(new java.awt.Color(149, 87, 29));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-24.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setToolTipText("Lưu");
        btnSave.setBorderPainted(false);
        btnSave.setIconTextGap(10);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(96, 56, 19));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cancel-24.png"))); // NOI18N
        btnCancel.setText("Thoát");
        btnCancel.setToolTipText("Thoát");
        btnCancel.setIconTextGap(10);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogNhanVienLayout = new javax.swing.GroupLayout(dialogNhanVien.getContentPane());
        dialogNhanVien.getContentPane().setLayout(dialogNhanVienLayout);
        dialogNhanVienLayout.setHorizontalGroup(
            dialogNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogNhanVienLayout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        dialogNhanVienLayout.setVerticalGroup(
            dialogNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNhanVienLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(1024, 500));
        setPreferredSize(new java.awt.Dimension(1024, 500));

        pnlNhanVien.setMinimumSize(new java.awt.Dimension(1024, 500));
        pnlNhanVien.setPreferredSize(new java.awt.Dimension(1024, 500));

        jPanel2.setBackground(new java.awt.Color(149, 87, 29));
        jPanel2.setMinimumSize(new java.awt.Dimension(793, 45));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnThem.setBackground(new java.awt.Color(149, 87, 29));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-24.png"))); // NOI18N
        btnThem.setToolTipText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.setFocusable(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThem.setLabel("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(100, 35));
        btnThem.setMinimumSize(new java.awt.Dimension(100, 35));
        btnThem.setPreferredSize(new java.awt.Dimension(100, 35));
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);

        btnSua.setBackground(new java.awt.Color(149, 87, 29));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pencil-drawing-24.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setToolTipText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.setFocusable(false);
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSua.setMaximumSize(new java.awt.Dimension(100, 35));
        btnSua.setMinimumSize(new java.awt.Dimension(100, 35));
        btnSua.setPreferredSize(new java.awt.Dimension(100, 35));
        btnSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(149, 87, 29));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-minus-24.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.setToolTipText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setFocusable(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoa.setMaximumSize(new java.awt.Dimension(100, 35));
        btnXoa.setMinimumSize(new java.awt.Dimension(100, 35));
        btnXoa.setPreferredSize(new java.awt.Dimension(100, 35));
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(149, 87, 29)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(txtSearch);
        jLabel1.setText("Tìm Nhân viên: ");
        jLabel1.setToolTipText("Tìm Nhân viên");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-24.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setBorder(null);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.setOpaque(false);
        jScrollPane1.setViewportView(tblNhanVien);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tổng số Nhân viên:");

        txtTongSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongSo.setText("...");
        txtTongSo.setMaximumSize(new java.awt.Dimension(100, 20));
        txtTongSo.setMinimumSize(new java.awt.Dimension(100, 20));
        txtTongSo.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTongSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        lblNhanVien.setText("Thêm Nhân viên");
        txtTenNV.setText("");
        buttonGroup1.clearSelection();
        txtChucVu.setText("");
        dateChooser.cleanup();
        txtDiaChi.setText("");
        txtSdt.setText("");
        
        if (btnSave.getActionListeners().length != 0) {
            for (ActionListener item : btnSave.getActionListeners()) {
                btnSave.removeActionListener(item);
            }
        }
        btnSave.addActionListener((ActionEvent e) -> {
            String tenNV = txtTenNV.getText().isBlank() ? "" : txtTenNV.getText();
            String gioiTinh = radioBtnNam.isSelected() ? "Nam" : radioBtnNu.isSelected() ? "Nữ" : "";
            String chucVu = txtChucVu.getText().isBlank() ? "" : txtChucVu.getText();
            Timestamp ngayVaoLam = dateChooser.getDate() == null ? new Timestamp(new Date().getTime()) : new Timestamp(dateChooser.getDate().getTime());
            String diaChi = txtDiaChi.getText().isBlank() ? "" : txtDiaChi.getText();
            String sdt = txtSdt.getText().isBlank() ? "" : txtSdt.getText();
            if (new NhanVien_BUS().insert(tenNV, gioiTinh, chucVu, ngayVaoLam, diaChi, sdt) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                dialogNhanVien.dispose();
                btnSave.setActionCommand("performed");
                loadTableNhanVien();
            }
        });
        dialogNhanVien.getRootPane().setDefaultButton(btnSave);
        dialogNhanVien.setLocationRelativeTo(null);
        dialogNhanVien.setModal(true);
        dialogNhanVien.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (tblNhanVien.getSelectedRowCount() == 0 || tblNhanVien.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn 1 nhân viên để sửa thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
        } else {
            int index = tblNhanVien.getSelectedRow();
            dtm = (DefaultTableModel) tblNhanVien.getModel();
            lblNhanVien.setText("Cập nhật Nhân viên");
            txtTenNV.setText(dtm.getValueAt(index, 1).toString());
            if (dtm.getValueAt(index, 2).toString().equals("Nam")) {
                radioBtnNam.setSelected(true);
            } else {
                radioBtnNu.setSelected(true);
            }
            txtChucVu.setText(dtm.getValueAt(index, 3).toString());
            try {
                dateChooser.setDate(sdf.parse(dtm.getValueAt(index, 4).toString()));
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtDiaChi.setText(dtm.getValueAt(index, 5).toString());
            txtSdt.setText(dtm.getValueAt(index, 6).toString());
            
            if (btnSave.getActionListeners().length != 0) {
                for (ActionListener item : btnSave.getActionListeners()) {
                    btnSave.removeActionListener(item);
                }
            }
            btnSave.addActionListener((ActionEvent e) -> {
                int maNV = Integer.parseInt(dtm.getValueAt(index, 0).toString());
                String tenNV = txtTenNV.getText().isBlank() ? "" : txtTenNV.getText();
                String gioiTinh = radioBtnNam.isSelected() ? "Nam" : radioBtnNu.isSelected() ? "Nữ" : "";
                String chucVu = txtChucVu.getText().isBlank() ? "" : txtChucVu.getText();
                Timestamp ngayVaoLam = dateChooser.getDate() == null ? new Timestamp(new Date().getTime()) : new Timestamp(dateChooser.getDate().getTime());
                String diaChi = txtDiaChi.getText().isBlank() ? "" : txtDiaChi.getText();
                String sdt = txtSdt.getText().isBlank() ? "" : txtSdt.getText();
                if (new NhanVien_BUS().update(maNV, tenNV, gioiTinh, chucVu, ngayVaoLam, diaChi, sdt) > 0) {
                    JOptionPane.showMessageDialog(null, "Cập nhật nhân viên thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    dialogNhanVien.dispose();
                    btnSave.setActionCommand("performed");
                    loadTableNhanVien();
                }
            });
            dialogNhanVien.getRootPane().setDefaultButton(btnSave);
            dialogNhanVien.setLocationRelativeTo(null);
            dialogNhanVien.setModal(true);
            dialogNhanVien.setVisible(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int[] rowSelected = tblNhanVien.getSelectedRows();
        if (rowSelected.length == 0)
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ít nhất 1 nhân viên để xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
        else {
            dtm = (DefaultTableModel) tblNhanVien.getModel();
            int chosen = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá " + rowSelected.length + " nhân viên không?", "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (chosen == JOptionPane.YES_OPTION) {
                NhanVien_BUS nv = new NhanVien_BUS();
                int rowAffected = 0;
                for (int i = 0; i < rowSelected.length; i++) {
                    if (nv.delete(Integer.parseInt(dtm.getValueAt(rowSelected[i], 0).toString())) > 0) {
                        rowAffected++;
                    }
                }
                if (rowAffected == rowSelected.length) {
                    JOptionPane.showMessageDialog(null, "Xoá thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
                loadTableNhanVien();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String strSearch = "^.*" + txtSearch.getText().toLowerCase() + ".*$";
        dtm = (DefaultTableModel) tblNhanVien.getModel();
        dtm.setRowCount(0);
        lstNhanVien.stream().filter(nv -> (String.valueOf(nv.getMaNV()).matches(strSearch) || nv.getTenNV().toLowerCase().matches(strSearch) || nv.getGioiTinh().toLowerCase().matches(strSearch) || nv.getChucVu().toLowerCase().matches(strSearch) || nv.getSdt().matches(strSearch))).forEachOrdered(nv -> {
            dtm.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinh(),
                nv.getChucVu(),
                sdf.format(nv.getNgayVaoLam()),
                nv.getDiaChi(),
                nv.getSdt()
            });
        });
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if ("performed".equalsIgnoreCase(btnSave.getActionCommand()) || (txtTenNV.getText().isBlank() && dateChooser.getDate() == null && txtSdt.getText().isBlank())) {
            dialogNhanVien.dispose();
        } else {
            int chosen = JOptionPane.showConfirmDialog(null, "Thông tin nhân viên chưa được lưu. Bạn có muốn lưu không?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (chosen == JOptionPane.NO_OPTION) {
                dialogNhanVien.dispose();
            } else if (chosen == JOptionPane.YES_OPTION) {
                btnSave.doClick();
                if ("performed".equalsIgnoreCase(btnSave.getActionCommand())) {
                    dialogNhanVien.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void dialogNhanVienWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogNhanVienWindowClosing
        if ("performed".equalsIgnoreCase(btnSave.getActionCommand()) || (txtTenNV.getText().isBlank() && dateChooser.getDate() == null && txtSdt.getText().isBlank())) {
            dialogNhanVien.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        } else {
            int chosen = JOptionPane.showConfirmDialog(null, "Thông tin nhân viên chưa được lưu. Bạn có muốn lưu không?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            switch (chosen) {
                case JOptionPane.NO_OPTION:
                    dialogNhanVien.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    break;
                case JOptionPane.CANCEL_OPTION:
                    dialogNhanVien.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                    break;
                case JOptionPane.YES_OPTION:
                    btnSave.doClick();
                    if ("performed".equals(btnSave.getActionCommand())) {
                        dialogNhanVien.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    }
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_dialogNhanVienWindowClosing
    
    private void loadTableNhanVien() {
        lstNhanVien = new NhanVien_BUS().getList();
        if (lstNhanVien.isEmpty()) {
            return;
        }
        
        tblNhanVien.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblNhanVien.getTableHeader().setReorderingAllowed(false);
        tblNhanVien.setRowHeight(24);
        tblNhanVien.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblNhanVien.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        //Set DefaultTableModel & add header table
        tblNhanVien.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });
        tblNhanVien.getModel().addTableModelListener((TableModelEvent e) -> {
            txtTongSo.setText(tblNhanVien.getRowCount() + "");
        });
        
        dtm = (DefaultTableModel) tblNhanVien.getModel();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Họ và Tên");
        dtm.addColumn("Giới tính");
        dtm.addColumn("Chức vụ");
        dtm.addColumn("Ngày vào làm");
        dtm.addColumn("Địa chỉ");
        dtm.addColumn("Số điện thoại");

        //Setting column width & turn off resizable
        tblNhanVien.getColumnModel().getColumn(0).setMinWidth(130);
        tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(130);
        for (int i = 0; i < 7; i++) {
            tblNhanVien.getColumnModel().getColumn(i).setResizable(false);
        }
        tblNhanVien.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        lstNhanVien.forEach(nv -> {
            dtm.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getGioiTinh(),
                nv.getChucVu(),
                sdf.format(nv.getNgayVaoLam()),
                nv.getDiaChi(),
                nv.getSdt()
            });
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    protected javax.swing.JButton btnSave;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JDialog dialogNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JRadioButton radioBtnNam;
    private javax.swing.JRadioButton radioBtnNu;
    private javax.swing.JTable tblNhanVien;
    protected javax.swing.JTextField txtChucVu;
    protected javax.swing.JTextField txtDiaChi;
    protected javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    protected javax.swing.JTextField txtTenNV;
    private javax.swing.JLabel txtTongSo;
    // End of variables declaration//GEN-END:variables
}
