/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacoffee.view.manage;

import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacoffee.bus.Luong_BUS;
import javacoffee.pojo.Luong_pojo;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kikkdt (KietDt)
 */
public class TinhLuongGUI extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private ArrayList<Luong_pojo> lstLuong = new ArrayList<>();
    private double luongCB = 25000;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public TinhLuongGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        dialogLuongCB = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        lblLuongCB = new javax.swing.JLabel();
        txtLuongCB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlChamCong = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLuongCB = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        dateTo = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTinhLuong = new javax.swing.JButton();

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1020, 407));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1020, 407));

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLuong.setOpaque(false);
        jScrollPane1.setViewportView(tblLuong);

        dialogLuongCB.setTitle("Cập nhật Lương cơ bản");
        dialogLuongCB.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png"))
        );
        dialogLuongCB.setMinimumSize(new java.awt.Dimension(400, 260));
        dialogLuongCB.setPreferredSize(new java.awt.Dimension(400, 260));
        dialogLuongCB.setResizable(false);
        dialogLuongCB.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogLuongCBWindowClosing(evt);
            }
        });

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 87, 29), 2, true));

        lblLuongCB.setBackground(new java.awt.Color(149, 87, 29));
        lblLuongCB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLuongCB.setForeground(new java.awt.Color(255, 255, 255));
        lblLuongCB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLuongCB.setText("Cập nhật Lương cơ bản");
        lblLuongCB.setOpaque(true);

        txtLuongCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLuongCB.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 56, 19));
        jLabel12.setText("Lương cơ bản:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 56, 19));
        jLabel13.setText("/giờ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLuongCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLuongCB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnSave.setBackground(new java.awt.Color(149, 87, 29));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-24.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setBorderPainted(false);
        btnSave.setIconTextGap(10);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(96, 56, 19));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cancel-24.png"))); // NOI18N
        btnCancel.setText("Thoát");
        btnCancel.setIconTextGap(10);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogLuongCBLayout = new javax.swing.GroupLayout(dialogLuongCB.getContentPane());
        dialogLuongCB.getContentPane().setLayout(dialogLuongCBLayout);
        dialogLuongCBLayout.setHorizontalGroup(
            dialogLuongCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogLuongCBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogLuongCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dialogLuongCBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        dialogLuongCBLayout.setVerticalGroup(
            dialogLuongCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogLuongCBLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogLuongCBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(1024, 500));
        setPreferredSize(new java.awt.Dimension(1024, 500));

        pnlChamCong.setMinimumSize(new java.awt.Dimension(1024, 500));
        pnlChamCong.setPreferredSize(new java.awt.Dimension(1024, 500));

        jPanel2.setBackground(new java.awt.Color(149, 87, 29));
        jPanel2.setMinimumSize(new java.awt.Dimension(793, 45));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnLuongCB.setBackground(new java.awt.Color(149, 87, 29));
        btnLuongCB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuongCB.setForeground(new java.awt.Color(255, 255, 255));
        btnLuongCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-business-management-24.png"))); // NOI18N
        btnLuongCB.setText("Lương cơ bản");
        btnLuongCB.setToolTipText("Điều chỉnh lương cơ bản");
        btnLuongCB.setBorderPainted(false);
        btnLuongCB.setFocusable(false);
        btnLuongCB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLuongCB.setMaximumSize(new java.awt.Dimension(160, 35));
        btnLuongCB.setMinimumSize(new java.awt.Dimension(160, 35));
        btnLuongCB.setPreferredSize(new java.awt.Dimension(160, 35));
        btnLuongCB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLuongCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongCBActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuongCB);

        btnXuatFile.setBackground(new java.awt.Color(149, 87, 29));
        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-pdf-24.png"))); // NOI18N
        btnXuatFile.setText("Xuất file");
        btnXuatFile.setToolTipText("Xuất file PDF");
        btnXuatFile.setBorderPainted(false);
        btnXuatFile.setFocusable(false);
        btnXuatFile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXuatFile.setMaximumSize(new java.awt.Dimension(120, 35));
        btnXuatFile.setMinimumSize(new java.awt.Dimension(120, 35));
        btnXuatFile.setPreferredSize(new java.awt.Dimension(120, 35));
        btnXuatFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });
        jPanel2.add(btnXuatFile);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(149, 87, 29)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setLabelFor(dateFrom);
        jLabel3.setText("Từ ngày:");
        jLabel3.setToolTipText("Ngày chấm công");

        dateFrom.setToolTipText("Chọn ngày chấm công");
        dateFrom.setDateFormatString("dd/MM/yyyy");
        dateFrom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateFrom.setIcon(new ImageIcon(getClass().getResource("/icons8-calendar-24.png")));
        dateFrom.setMaxSelectableDate(new java.util.Date());
        dateFrom.setMaximumSize(new java.awt.Dimension(200, 30));
        dateFrom.setMinimumSize(new java.awt.Dimension(200, 30));
        dateFrom.setPreferredSize(new java.awt.Dimension(200, 30));

        dateTo.setToolTipText("Chọn ngày chấm công");
        dateTo.setDateFormatString("dd/MM/yyyy");
        dateTo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dateTo.setIcon(new ImageIcon(getClass().getResource("/icons8-calendar-24.png")));
        dateTo.setMaxSelectableDate(new java.util.Date());
        dateTo.setMaximumSize(new java.awt.Dimension(200, 30));
        dateTo.setMinimumSize(new java.awt.Dimension(200, 30));
        dateTo.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setLabelFor(dateFrom);
        jLabel4.setText("đến ngày:");
        jLabel4.setToolTipText("Ngày chấm công");

        jPanel3.setMinimumSize(new java.awt.Dimension(1020, 407));
        jPanel3.setPreferredSize(new java.awt.Dimension(1020, 407));
        jPanel3.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chưa có dữ liệu...");
        jLabel1.setToolTipText("Chưa có dữ liệu...");
        jPanel3.add(jLabel1, "card2");

        btnTinhLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-estimate-24.png"))); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTinhLuong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTinhLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlChamCongLayout = new javax.swing.GroupLayout(pnlChamCong);
        pnlChamCong.setLayout(pnlChamCongLayout);
        pnlChamCongLayout.setHorizontalGroup(
            pnlChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlChamCongLayout.setVerticalGroup(
            pnlChamCongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamCongLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        if (lstLuong.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lỗi, danh sách lương hiện đang trống.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            return;
        }

        //Convert ArrayList to JRBeanCollectionDataSource
        JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(lstLuong);

        //Map to hold Jasper report parametes
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("luongCB", luongCB);
        parameters.put("CollectionBeanParam", dataSource);

        try {
            //Read jrxml file and creating JasperDesign object
            InputStream input = new FileInputStream(new File("src/javacoffee/view/report/reportLuong.jrxml"));
            JasperDesign jasperDesign = JRXmlLoader.load(input);

            //Compiling jrxml file
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);

            //Generate PDF
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());

            //Display PDF file
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setTitle("Java Coffee");
            jasperViewer.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png")));
            jasperViewer.setVisible(true);

        } catch (FileNotFoundException | JRException ex) {
            Logger.getLogger(TinhLuongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        Timestamp from, to;
        try {
            from = new Timestamp(sdf.parse(sdf.format(dateFrom.getDate())).getTime());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            return;
        }
        try {
            to = new Timestamp(sdf.parse(sdf.format(dateTo.getDate())).getTime());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ngày kết thúc không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            return;
        }

        loadTableTinhLuong(from, to);
        jPanel3.removeAll();
        jPanel3.add(jScrollPane1);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnLuongCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongCBActionPerformed
        txtLuongCB.setText(String.format("%.0f", luongCB));

        dialogLuongCB.getRootPane().setDefaultButton(btnSave);
        dialogLuongCB.setLocationRelativeTo(null);
        dialogLuongCB.setModal(true);
        dialogLuongCB.setVisible(true);
    }//GEN-LAST:event_btnLuongCBActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if ("performed".equalsIgnoreCase(btnSave.getActionCommand()) || txtLuongCB.getText().isBlank()) {
            dialogLuongCB.dispose();
        } else {
            int chosen = JOptionPane.showConfirmDialog(null, "Lương cơ bản chưa được lưu. Lưu?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (chosen == JOptionPane.NO_OPTION) {
                dialogLuongCB.dispose();
            } else if (chosen == JOptionPane.YES_OPTION) {
                btnSave.doClick();
                if ("performed".equalsIgnoreCase(btnSave.getActionCommand())) {
                    dialogLuongCB.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void dialogLuongCBWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogLuongCBWindowClosing
        if ("performed".equalsIgnoreCase(btnSave.getActionCommand()) || txtLuongCB.getText().isBlank()) {
            dialogLuongCB.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        } else {
            int chosen = JOptionPane.showConfirmDialog(null, "Lương cơ bản chưa được lưu. Lưu?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            switch (chosen) {
                case JOptionPane.NO_OPTION:
                    dialogLuongCB.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    break;
                case JOptionPane.CANCEL_OPTION:
                    dialogLuongCB.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                    break;
                case JOptionPane.YES_OPTION:
                    btnSave.doClick();
                    if ("performed".equalsIgnoreCase(btnSave.getActionCommand())) {
                        dialogLuongCB.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    }
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_dialogLuongCBWindowClosing

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtLuongCB.getText().matches("^[0-9]+$")) {
            if (Double.parseDouble(txtLuongCB.getText()) >= 0) {
                luongCB = Double.parseDouble(txtLuongCB.getText());
                btnSave.setActionCommand("performed");
                dialogLuongCB.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi, lương cơ bản không được âm.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi, lương cơ bản phải là số.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void loadTableTinhLuong(Timestamp from, Timestamp to) {
        lstLuong = new Luong_BUS().calcLuong(luongCB, from, to);
        if (lstLuong.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lỗi, danh sách lương hiện đang trống.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            return;
        }

        tblLuong.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblLuong.getTableHeader().setReorderingAllowed(false);
        tblLuong.setRowHeight(24);
        tblLuong.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblLuong.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        //Set DefaultTableModel & add header table
        tblLuong.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });

        dtm = (DefaultTableModel) tblLuong.getModel();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        dtm.addColumn("Mã Nhân viên");
        dtm.addColumn("Tên Nhân viên");
        dtm.addColumn("Tổng ca làm");
        dtm.addColumn("Thành tiền");

        //Setting column width & turn off resizable
        for (int i = 0; i < 4; i++) {
            tblLuong.getColumnModel().getColumn(i).setResizable(false);
        }
        tblLuong.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        lstLuong.forEach((Luong_pojo luong) -> {
            dtm.addRow(new Object[]{
                luong.getMaNV(),
                luong.getTenNV(),
                luong.getTongCaLam(),
                String.format("%,.0f", luong.getThanhTien())
            });
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLuongCB;
    protected javax.swing.JButton btnSave;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXuatFile;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JDialog dialogLuongCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLuongCB;
    private javax.swing.JPanel pnlChamCong;
    private javax.swing.JTable tblLuong;
    protected javax.swing.JTextField txtLuongCB;
    // End of variables declaration//GEN-END:variables
}
