/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacoffee.view.feature;

import java.sql.Timestamp;
import javacoffee.pojo.Ban_pojo;
import javacoffee.pojo.KhuVuc_pojo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacoffee.bus.Ban_BUS;
import javacoffee.bus.CTHoaDon_BUS;
import javacoffee.bus.DanhMuc_BUS;
import javacoffee.bus.HoaDon_BUS;
import javacoffee.bus.KhachHang_BUS;
import javacoffee.bus.KhuVuc_BUS;
import javacoffee.bus.NhanVien_BUS;
import javacoffee.bus.SanPham_BUS;
import javacoffee.bus.ThanhToan_BUS;
import javacoffee.bus.XuatCTHoaDon_BUS;
import javacoffee.pojo.DanhMuc_pojo;
import javacoffee.pojo.SanPham_pojo;
import javacoffee.pojo.TaiKhoan_pojo;
import javacoffee.pojo.ThanhToan_pojo;
import javacoffee.view.manage.TinhLuongGUI;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kikkdt (KietDt)
 */
public class OrderGUI extends javax.swing.JPanel {

    private JButton tableSelected = null;
    private ThanhToan_pojo thanhtoan = null;
    private TaiKhoan_pojo account;
    private DefaultTableModel dtm;
    private static SanPham_BUS sp = new SanPham_BUS();
    private static KhachHang_BUS kh = new KhachHang_BUS();
    private static NhanVien_BUS nv = new NhanVien_BUS();
    private static XuatCTHoaDon_BUS xuatCTHD = new XuatCTHoaDon_BUS();

    public TaiKhoan_pojo getAccount() {
        return account;
    }

    public void setAccount(TaiKhoan_pojo account) {
        this.account = account;
    }

    /**
     * @param account use to identity user
     */
    public OrderGUI(TaiKhoan_pojo account) {
        initComponents();
        loadPanelBan();
        pnlBillEmpty.setVisible(false);
        bgrBill.setVisible(true);
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBillEmpty = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTeNBan = new javax.swing.JLabel();
        lblKhuVuc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        btnTroVe = new javax.swing.JButton();
        pnlBillServed = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTeNBan1 = new javax.swing.JLabel();
        lblKhuVuc1 = new javax.swing.JLabel();
        lblTrangThai1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblGioDen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlBan = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        bgrBill = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        bgrMenu = new javax.swing.JLabel();
        tabPnlMenu = new javax.swing.JTabbedPane();

        pnlBillEmpty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 56, 19), 2, true));
        pnlBillEmpty.setPreferredSize(new java.awt.Dimension(270, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-medium.png"))); // NOI18N

        lblTeNBan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTeNBan.setForeground(new java.awt.Color(96, 56, 19));
        lblTeNBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeNBan.setText("Tên Bàn");

        lblKhuVuc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblKhuVuc.setForeground(new java.awt.Color(96, 56, 19));
        lblKhuVuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhuVuc.setText("Khu vực");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 97, 0));
        jLabel6.setText("Trạng thái bàn: ");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTrangThai.setText("Trạng thái");

        btnOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(96, 56, 19));
        btnOrder.setText("Order >>");
        btnOrder.setPreferredSize(new java.awt.Dimension(100, 50));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnTroVe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTroVe.setForeground(new java.awt.Color(96, 56, 19));
        btnTroVe.setText("<< Trở về");
        btnTroVe.setPreferredSize(new java.awt.Dimension(100, 50));
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBillEmptyLayout = new javax.swing.GroupLayout(pnlBillEmpty);
        pnlBillEmpty.setLayout(pnlBillEmptyLayout);
        pnlBillEmptyLayout.setHorizontalGroup(
            pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillEmptyLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillEmptyLayout.createSequentialGroup()
                        .addComponent(btnTroVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBillEmptyLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(pnlBillEmptyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTeNBan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBillEmptyLayout.setVerticalGroup(
            pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillEmptyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTeNBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhuVuc)
                .addGap(18, 18, 18)
                .addGroup(pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTrangThai))
                .addGap(63, 63, 63)
                .addGroup(pnlBillEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );

        pnlBillServed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 56, 19), 2, true));
        pnlBillServed.setPreferredSize(new java.awt.Dimension(270, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-medium.png"))); // NOI18N

        lblTeNBan1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTeNBan1.setForeground(new java.awt.Color(96, 56, 19));
        lblTeNBan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeNBan1.setText("Tên Bàn");

        lblKhuVuc1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblKhuVuc1.setForeground(new java.awt.Color(96, 56, 19));
        lblKhuVuc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhuVuc1.setText("Khu vực");

        lblTrangThai1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangThai1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangThai1.setText("Trạng thái");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(96, 56, 19));
        jLabel8.setText("Giờ đến: ");

        lblGioDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGioDen.setText("Giờ đến");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(96, 56, 19));
        jLabel9.setText("Tổng tiền: ");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(252, 97, 0));
        lblTongTien.setText("Tổng tiền");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 56, 19));
        jLabel10.setText("Khách hàng: ");

        txtKhachHang.setEditable(false);
        txtKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtKhachHang.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 56, 19));
        jLabel11.setText("Giảm giá: ");

        lblGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGiamGia.setText("Giảm giá");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("THÀNH TIỀN: ");

        lblThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(255, 0, 0));
        lblThanhTien.setText("THÀNH TIỀN");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(96, 56, 19));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-visa-24.png"))); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-24.png"))); // NOI18N
        btnSearch.setBorderPainted(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBillServedLayout = new javax.swing.GroupLayout(pnlBillServed);
        pnlBillServed.setLayout(pnlBillServedLayout);
        pnlBillServedLayout.setHorizontalGroup(
            pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlBillServedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeNBan1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblKhuVuc1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblTrangThai1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGioDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillServedLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlBillServedLayout.setVerticalGroup(
            pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillServedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addComponent(lblTeNBan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKhuVuc1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTrangThai1)))
                .addGap(18, 18, 18)
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGioDen))
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBillServedLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblGiamGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBillServedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblThanhTien))
                .addGap(13, 13, 13)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        setPreferredSize(new java.awt.Dimension(1024, 500));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 56, 19), 2, true));

        jPanel7.setBackground(new java.awt.Color(49, 186, 124));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bàn trống");

        jPanel8.setBackground(new java.awt.Color(226, 76, 75));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Đang phục vụ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBan)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCenter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 56, 19), 2, true));
        pnlCenter.setMinimumSize(new java.awt.Dimension(270, 500));
        pnlCenter.setPreferredSize(new java.awt.Dimension(270, 500));
        pnlCenter.setLayout(new java.awt.CardLayout());

        bgrBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgrBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill-panel.png"))); // NOI18N
        bgrBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bgrBill.setMaximumSize(new java.awt.Dimension(0, 0));
        bgrBill.setMinimumSize(new java.awt.Dimension(270, 500));
        bgrBill.setPreferredSize(new java.awt.Dimension(270, 500));
        pnlCenter.add(bgrBill, "card2");

        pnlRight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(96, 56, 19), 2, true));
        pnlRight.setMinimumSize(new java.awt.Dimension(364, 500));
        pnlRight.setPreferredSize(new java.awt.Dimension(364, 500));
        pnlRight.setLayout(new java.awt.CardLayout());

        bgrMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgrMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-menu.png"))); // NOI18N
        bgrMenu.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlRight.add(bgrMenu, "card3");

        tabPnlMenu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPnlMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabPnlMenu.setMinimumSize(new java.awt.Dimension(364, 500));
        tabPnlMenu.setPreferredSize(new java.awt.Dimension(364, 500));
        pnlRight.add(tabPnlMenu, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadPnlRight(boolean displayMenu) {
        pnlRight.removeAll();
        if (displayMenu) {
            if (tabPnlMenu.getTabCount() == 0) {
                loadMenu();
            }
            pnlRight.add(tabPnlMenu);
        } else {
            pnlRight.add(bgrMenu);
        }
        pnlRight.repaint();
        pnlRight.revalidate();
    }

    private void loadPnlCenter(boolean displayBillEmpty) {
        pnlCenter.removeAll();
        if (displayBillEmpty) {
            pnlCenter.add(pnlBillEmpty);
        } else {
            pnlCenter.add(bgrBill);
        }
        pnlCenter.repaint();
        pnlCenter.revalidate();
    }

    private void loadPanelBan() {
        ArrayList<KhuVuc_pojo> lstKhuVuc = new KhuVuc_BUS().getList();
        if (lstKhuVuc.isEmpty()) {
            return;
        }
        int i = 0;
        for (KhuVuc_pojo kv : lstKhuVuc) {
            JLabel lblTabKhuVuc = new JLabel(kv.getTenKhuVuc());
            lblTabKhuVuc.setPreferredSize(new Dimension(70, 30));
            lblTabKhuVuc.setFont(new Font("Segoe UI", Font.BOLD, 14));

            ArrayList<Ban_pojo> lstBan = new Ban_BUS().getList(kv.getMaKhuVuc());
            if (lstBan.isEmpty()) {
                return;
            }
            JPanel pnlListBan = new JPanel();
            pnlListBan.setPreferredSize(pnlBan.getPreferredSize());
            pnlListBan.setMaximumSize(pnlBan.getMaximumSize());
            pnlListBan.setMinimumSize(pnlBan.getMinimumSize());
            pnlListBan.setLayout(new FlowLayout(FlowLayout.LEFT));

            lstBan.stream().map(ban -> {
                JButton btnBan = new JButton(ban.getTenBan());
                btnBan.setBorder(null);
                btnBan.setBackground(ban.isTrangThai() == true ? new Color(226, 76, 75) : new Color(49, 186, 124));
                btnBan.setForeground(Color.white);
                btnBan.setFont(new Font("Segoe UI", Font.BOLD, 17));
                btnBan.setHorizontalAlignment(0);
                Icon icon = new ImageIcon(getClass().getResource("/table.png"));
                btnBan.setIcon(icon);
                btnBan.setHorizontalTextPosition(0);
                btnBan.setVerticalTextPosition(3);
                btnBan.setActionCommand(ban.getMaBan() + "");
                //Add event for each table
                btnBan.addActionListener((ActionEvent e) -> {
                    tableSelected = btnBan;
                    if (ban.isTrangThai()) {
                        loadBillServed(ban.getMaBan());
                        loadPnlRight(true);
                    } else {
                        thanhtoan = null;
                        lblTeNBan.setText(ban.getTenBan());
                        lblKhuVuc.setText(kv.getTenKhuVuc());
                        lblTrangThai.setText("Bàn trống");
                        loadPnlCenter(true);
                        loadPnlRight(false);
                    }
                });
                return btnBan;
            }).forEachOrdered(btnBan -> {
                pnlListBan.add(btnBan);
            });
            pnlBan.addTab("", pnlListBan);
            pnlBan.setTabComponentAt(i++, lblTabKhuVuc);
        }
    }

    private void loadBillServed(int maBan) {
        //Get bill info is "unpaid" with table number selected
        thanhtoan = new ThanhToan_BUS().getThanhToan(maBan);
        if (thanhtoan == null) {
            return;
        }

        lblTeNBan1.setText(thanhtoan.getBan().getTenBan());
        lblTrangThai1.setText(thanhtoan.getBan().isTrangThai() == true ? "Đang phục vụ" : "Bàn trống");
        lblKhuVuc1.setText(thanhtoan.getKhuvuc().getTenKhuVuc());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        lblGioDen.setText(sdf.format(thanhtoan.getHoadon().getNgayXuatHD()));
        String tenKH = kh.getTenKH(thanhtoan.getHoadon().getMaKH());
        txtKhachHang.setText(tenKH);
        lblTongTien.setText(String.format("%,.0f", thanhtoan.getHoadon().getTongTien()));
        lblGiamGia.setText(String.format("%,.0f", thanhtoan.getHoadon().getGiamGia()));
        lblThanhTien.setText(String.format("%,.0f", thanhtoan.getHoadon().getThanhTien()));

        tblProducts.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblProducts.getTableHeader().setReorderingAllowed(false);
        tblProducts.setRowHeight(24);
        tblProducts.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblProducts.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        //Set DefaultTableModel & add header table
        tblProducts.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });
        dtm = (DefaultTableModel) tblProducts.getModel();
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        dtm.addColumn("Tên");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Đơn giá");
        dtm.addColumn("Thành tiền");

        //Setting column width & turn off resizable
        tblProducts.getColumnModel().getColumn(0).setPreferredWidth(140);
        tblProducts.getColumnModel().getColumn(1).setPreferredWidth(60);
        for (int i = 0; i < 4; i++) {
            tblProducts.getColumnModel().getColumn(i).setResizable(false);
        }
        tblProducts.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        thanhtoan.getCtHoaDon().forEach(cthd -> {
            dtm.addRow(new Object[]{
                sp.getTenSP(cthd.getMaSP()),
                cthd.getSoLuong(),
                String.format("%,.0f", sp.getGiaBan(cthd.getMaSP())),
                String.format("%,.0f", cthd.getThanhTien())
            });
        });
        pnlCenter.removeAll();
        pnlCenter.add(pnlBillServed);
        pnlCenter.repaint();
        pnlCenter.revalidate();
    }

    private void loadMenu() {
        ArrayList<DanhMuc_pojo> lstDanhMuc = new DanhMuc_BUS().getList();
        if (lstDanhMuc.isEmpty()) {
            return;
        }
        for (DanhMuc_pojo dm : lstDanhMuc) {
            JLabel lblTabDanhMuc = new JLabel(dm.getTenDanhMuc());
            lblTabDanhMuc.setPreferredSize(new Dimension(80, 70));
            lblTabDanhMuc.setFont(new Font("Segoe UI", Font.BOLD, 14));

            ArrayList<SanPham_pojo> lstSanPham = new SanPham_BUS().getList(dm.getMaDanhMuc());
            if (lstSanPham.isEmpty()) {
                return;
            }
            JPanel pnlListMenu = new JPanel();
//            pnlListMenu.setMaximumSize(pnlMenu.getMaximumSize());
//            pnlListMenu.setMinimumSize(pnlMenu.getMinimumSize());
            pnlListMenu.setPreferredSize(new Dimension(230, 500));
            pnlListMenu.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));

            lstSanPham.stream().map(itemSP -> {
                JButton btnMenu = new JButton(itemSP.getTenSanPham());
                btnMenu.setBorder(null);
                btnMenu.setFont(new Font("Segoe UI", Font.PLAIN, 17));
                btnMenu.setHorizontalAlignment(0);
                btnMenu.setToolTipText(itemSP.getTenSanPham());
                ImageIcon icon;
                if (itemSP.getHinhAnh() == null) {
                    icon = new ImageIcon(getClass().getResource("/no-data.png"));
                } else {
                    icon = new ImageIcon(getClass().getResource("/" + itemSP.getHinhAnh()));
                    Image image = icon.getImage();
                    Image newImage = image.getScaledInstance(180, 120, java.awt.Image.SCALE_SMOOTH);
                    icon = new ImageIcon(newImage);
                }
                btnMenu.setIcon(icon);
                btnMenu.setHorizontalTextPosition(SwingConstants.CENTER);
                btnMenu.setVerticalTextPosition(SwingConstants.BOTTOM);
                btnMenu.setActionCommand(itemSP.getMaSanPham() + "");
                return btnMenu;
            }).map(btnMenu -> {
                btnMenu.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (e.getClickCount() == 2 && !e.isConsumed()) {
                            e.consume();
                            if (new CTHoaDon_BUS().insert(thanhtoan.getHoadon().getMaHD(), Integer.parseInt(btnMenu.getActionCommand())) > 0) {
                                loadBillServed(Integer.parseInt(tableSelected.getActionCommand()));
                            } else {
                                JOptionPane.showMessageDialog(null, "Order thất bại :(", "Lỗi gọi món", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
                            }
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                    }
                });
                return btnMenu;
            }).forEachOrdered(btnMenu -> {
                pnlListMenu.add(btnMenu);
            });
            tabPnlMenu.addTab("", pnlListMenu);
            tabPnlMenu.setTabComponentAt(dm.getMaDanhMuc() - 1, lblTabDanhMuc);
            tabPnlMenu.setToolTipTextAt(dm.getMaDanhMuc() - 1, lblTabDanhMuc.getText());
        }
    }

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        //Add new Bill
        new HoaDon_BUS().insert(account.getMaNV(), Integer.parseInt(tableSelected.getActionCommand()));
        int indexCurrent = pnlBan.getSelectedIndex();
        pnlBan.removeAll();
        loadPanelBan();
        pnlBan.setSelectedIndex(indexCurrent);

        //Refresh panel Center
        loadBillServed(Integer.parseInt(tableSelected.getActionCommand()));
        //Load menu
        loadPnlRight(true);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        //Reset background panel Center
        loadPnlCenter(false);
        //Reset background panel Right
        loadPnlRight(false);
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int indexRow = tblProducts.getSelectedRow();
            DialogAmount dlg = new DialogAmount(null, true);
            dlg.txtAmount.setText(dtm.getValueAt(indexRow, 1) + "");
            dlg.btnSave.addActionListener((ActionEvent e) -> {
                int soLuong = Integer.parseInt(dlg.txtAmount.getText());
                String tenSP = dtm.getValueAt(indexRow, 0).toString();
                int maSP = sp.getMaSP(tenSP);
                int maBan = Integer.parseInt(tableSelected.getActionCommand());
                if (soLuong > 0) {
                    if (new CTHoaDon_BUS().update(thanhtoan.getHoadon().getMaHD(), maSP, soLuong) > 0) {
                        dlg.btnSave.setActionCommand("performed");
                        dlg.dispose();
                        loadBillServed(maBan);
                    } else {
                        JOptionPane.showMessageDialog(null, "Lưu không thành công.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
                    }
                } else {
                    if (new CTHoaDon_BUS().delete(thanhtoan.getHoadon().getMaHD(), maSP) > 0) {
                        dlg.btnSave.setActionCommand("performed");
                        JOptionPane.showMessageDialog(null, "Xoá thành công.", "Chúc mừng", JOptionPane.INFORMATION_MESSAGE);
                        dlg.dispose();
                        loadBillServed(maBan);
                    } else {
                        JOptionPane.showMessageDialog(null, "Xoá không thành công.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
                    }
                }
            });
            dlg.getRootPane().setDefaultButton(dlg.btnSave);
            dlg.setLocationRelativeTo(null);
            dlg.setVisible(true);
        }
    }//GEN-LAST:event_tblProductsMouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        int maHD = thanhtoan.getHoadon().getMaHD();
        String tenKH = kh.getTenKH(thanhtoan.getHoadon().getMaKH());
        int diemTichLuy = kh.getDiemTichLuy(thanhtoan.getHoadon().getMaKH());
        String tenNV = nv.getTenNhanVien(thanhtoan.getHoadon().getMaNV());
        Timestamp ngayXuatHD = thanhtoan.getHoadon().getNgayXuatHD();
        String tenBan = thanhtoan.getBan().getTenBan();
        double tongTien = thanhtoan.getHoadon().getTongTien();
        double giamGia = thanhtoan.getHoadon().getGiamGia();
        double thanhTien = thanhtoan.getHoadon().getThanhTien();

        //Dialog payment
        DialogPayment payment = new DialogPayment(null, true, thanhTien);
        payment.btnThanhToan.addActionListener((e) -> {
            if (payment.txtTienDua.getText().isBlank() || payment.getTienTra() < 0) {
                JOptionPane.showMessageDialog(null, "Tiền khách thanh toán không đúng.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
                return;
            }

            String tienDua = String.format("%,.0f VNĐ", Double.parseDouble(payment.txtTienDua.getText()));
            String tienTra = payment.txtTienTra.getText();

            if (new ThanhToan_BUS().completeThanhToan(thanhtoan.getHoadon().getMaHD(), thanhtoan.getBan().getMaBan()) > 0) {
                payment.dispose();

                //Convert ArrayList to JRBeanCollectionDataSource
                JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(xuatCTHD.getList(maHD));

                //Map to hold Jasper report parametes
                Map<String, Object> parameters = new HashMap<>();
                parameters.put("maHD", maHD);
                parameters.put("tenKH", tenKH);
                parameters.put("diemTichLuy", diemTichLuy);
                parameters.put("tenNV", tenNV);
                parameters.put("ngayXuatHD", ngayXuatHD);
                parameters.put("tenBan", tenBan);
                parameters.put("tongTien", tongTien);
                parameters.put("giamGia", giamGia);
                parameters.put("thanhTien", thanhTien);
                parameters.put("tienDua", tienDua);
                parameters.put("tienTra", tienTra);
                parameters.put("CollectionBeanParam", dataSource);

                try {
                    //Read jrxml file and creating JasperDesign object
                    InputStream input = new FileInputStream(new File("src/javacoffee/view/report/reportHoaDon.jrxml"));
                    JasperDesign jasperDesign = JRXmlLoader.load(input);

                    //Compiling jrxml file
                    JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);

                    //Generate PDF
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());

                    //Display PDF file
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
                    jasperViewer.setTitle("Java Coffee");
                    jasperViewer.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png")));
                    jasperViewer.setVisible(true);

                } catch (FileNotFoundException | JRException ex) {
                    Logger.getLogger(TinhLuongGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "THANH TOÁN THẤT BẠI.", "Lỗi", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
            }
        });

        payment.setLocationRelativeTo(null);
        payment.setVisible(true);
        int indexCurrent = pnlBan.getSelectedIndex();
        pnlBan.removeAll();
        loadPanelBan();
        pnlBan.setSelectedIndex(indexCurrent);
        loadPnlCenter(true);
        loadPnlRight(false);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DialogCustomer dlg = new DialogCustomer(null, true);
        dlg.tblKhachHang.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && !e.isConsumed()) {
                    e.consume();
                    int rowSelected = dlg.tblKhachHang.getSelectedRow();
                    txtKhachHang.setText(dlg.dtm.getValueAt(rowSelected, 2).toString());
                    int maKH = Integer.parseInt(dlg.dtm.getValueAt(rowSelected, 1).toString());
                    new HoaDon_BUS().update(thanhtoan.getHoadon().getMaHD(), maKH);
                    loadBillServed(Integer.parseInt(tableSelected.getActionCommand()));
                    dlg.dispose();
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dlg.setLocationRelativeTo(null);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgrBill;
    private javax.swing.JLabel bgrMenu;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblGioDen;
    private javax.swing.JLabel lblKhuVuc;
    private javax.swing.JLabel lblKhuVuc1;
    private javax.swing.JLabel lblTeNBan;
    private javax.swing.JLabel lblTeNBan1;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblTrangThai1;
    private javax.swing.JTabbedPane pnlBan;
    private javax.swing.JPanel pnlBillEmpty;
    private javax.swing.JPanel pnlBillServed;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTabbedPane tabPnlMenu;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtKhachHang;
    // End of variables declaration//GEN-END:variables
}
