/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacoffee.view;

import java.awt.Dimension;
import javacoffee.view.feature.OrderGUI;
import java.awt.Toolkit;
import javacoffee.pojo.TaiKhoan_pojo;
import javacoffee.view.feature.HoaDonGUI;
import javacoffee.view.manage.BanGUI;
import javacoffee.view.manage.CaLamGUI;
import javacoffee.view.manage.ChamCongGUI;
import javacoffee.view.manage.DanhMucGUI;
import javacoffee.view.manage.KhuVucGUI;
import javacoffee.view.manage.NguyenLieuGUI;
import javacoffee.view.manage.NhaCungCapGUI;
import javacoffee.view.manage.NhanVienGUI;
import javacoffee.view.manage.TaiKhoanGUI;
import javacoffee.view.manage.SanPhamGUI;
import javacoffee.view.manage.TinhLuongGUI;
import javacoffee.view.feature.MemberGUI;
import javacoffee.view.manage.ThongKeGUI;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kikkdt (KietDt)
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static TaiKhoan_pojo account;
    
    public TaiKhoan_pojo getAccount() {
        return account;
    }
    
    public void setAccount(TaiKhoan_pojo account) {
        MainGUI.account = account;
    }

    /**
     * Creates new form MainGUI
     */
    public MainGUI(TaiKhoan_pojo account) {
        initComponents();
        if (account.getIdLoaiTK() == 2) {
            tabPanelMain.setEnabledAt(1, false);
        }
        MainGUI.account = account;
        mnTaiKhoan.setText("Xin chào, " + account.getTenHienThi());
        mnTaiKhoan.setMaximumSize(new Dimension(mnTaiKhoan.getText().length() * 7, 19));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHienThi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoaiTK = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        tabPanelMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        btnNhapHang = new javax.swing.JButton();
        pnlFeature = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        btnCaLam = new javax.swing.JButton();
        btnChamCong = new javax.swing.JButton();
        btnTinhLuong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnKhuVuc = new javax.swing.JButton();
        btnBan = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnDanhMuc = new javax.swing.JButton();
        btnThucDon = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnNCC = new javax.swing.JButton();
        btnNguyenLieu = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        pnlManage = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnTaiKhoan = new javax.swing.JMenu();
        mnItemDangXuat = new javax.swing.JMenuItem();
        mnuItemInfoAcc = new javax.swing.JMenuItem();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("Thông tin tài khoản");
        jDialog1.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png"))
        );
        jDialog1.setMinimumSize(new java.awt.Dimension(400, 315));
        jDialog1.setModal(true);
        jDialog1.setPreferredSize(new java.awt.Dimension(400, 315));
        jDialog1.setResizable(false);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(149, 87, 29), 2, true));

        lblTitle.setBackground(new java.awt.Color(149, 87, 29));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thông tin tài khoản");
        lblTitle.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenDangNhap.setEnabled(false);
        txtTenDangNhap.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tên hiển thị:");

        txtTenHienThi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTenHienThi.setEnabled(false);
        txtTenHienThi.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã nhân viên:");

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaNV.setEnabled(false);
        txtMaNV.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Loại tài khoản:");

        txtLoaiTK.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLoaiTK.setEnabled(false);
        txtLoaiTK.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenDangNhap)
                    .addComponent(txtTenHienThi)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLoaiTK))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoaiTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(96, 56, 19));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cancel-24.png"))); // NOI18N
        btnCancel.setText("Thoát");
        btnCancel.setIconTextGap(10);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Coffee");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/logo-icon.png"))
        );
        setMinimumSize(new java.awt.Dimension(1045, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tabPanelMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabPanelMain.setMinimumSize(new java.awt.Dimension(1025, 579));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        btnOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-food-donor-24.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setToolTipText("Gọi món");
        btnOrder.setBorderPainted(false);
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnOrder.setIconTextGap(7);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel14.add(btnOrder);

        btnMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-membership-card-24.png"))); // NOI18N
        btnMember.setText("Member");
        btnMember.setToolTipText("Đăng ký thành viên");
        btnMember.setBorderPainted(false);
        btnMember.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMember.setIconTextGap(7);
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
        jPanel14.add(btnMember);

        jPanel9.add(jPanel14);

        jPanel15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-order-history-24.png"))); // NOI18N
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setToolTipText("Lịch sử hóa đơn");
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHoaDon.setIconTextGap(7);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jPanel15.add(btnHoaDon);

        jPanel9.add(jPanel15);

        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        btnNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-buy-24.png"))); // NOI18N
        btnNhapHang.setText("Nhập nguyên liệu");
        btnNhapHang.setToolTipText("Nhập nguyên liệu");
        btnNhapHang.setBorderPainted(false);
        btnNhapHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhapHang.setIconTextGap(7);
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });
        jPanel16.add(btnNhapHang);

        jPanel9.add(jPanel16);

        jPanel1.add(jPanel9, java.awt.BorderLayout.NORTH);

        pnlFeature.setLayout(new java.awt.CardLayout());
        jPanel1.add(pnlFeature, java.awt.BorderLayout.CENTER);

        tabPanelMain.addTab("Chức năng", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-staff-24.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setToolTipText("Nhân viên");
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnCaLam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCaLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-schedule-24.png"))); // NOI18N
        btnCaLam.setText("Ca làm");
        btnCaLam.setToolTipText("Ca làm việc");
        btnCaLam.setBorderPainted(false);
        btnCaLam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCaLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaLamActionPerformed(evt);
            }
        });

        btnChamCong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChamCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-time-card-24.png"))); // NOI18N
        btnChamCong.setText("Chấm công");
        btnChamCong.setToolTipText("Chấm công");
        btnChamCong.setBorderPainted(false);
        btnChamCong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChamCong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongActionPerformed(evt);
            }
        });

        btnTinhLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTinhLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-estimate-24.png"))); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.setToolTipText("Tính lương định kỳ");
        btnTinhLuong.setBorderPainted(false);
        btnTinhLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTinhLuong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCaLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(btnChamCong)
                .addGap(0, 0, 0)
                .addComponent(btnTinhLuong))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnNhanVien)
                        .addGap(0, 0, 0)
                        .addComponent(btnCaLam))
                    .addComponent(btnChamCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTinhLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnKhuVuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-vastu-consultancy-24.png"))); // NOI18N
        btnKhuVuc.setText("Khu vực");
        btnKhuVuc.setToolTipText("Khu vực");
        btnKhuVuc.setBorderPainted(false);
        btnKhuVuc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuVucActionPerformed(evt);
            }
        });

        btnBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-table-24.png"))); // NOI18N
        btnBan.setText("Bàn");
        btnBan.setToolTipText("Bàn");
        btnBan.setBorderPainted(false);
        btnBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnKhuVuc)
                .addGap(0, 0, 0)
                .addComponent(btnBan))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-questionnaire-24.png"))); // NOI18N
        btnDanhMuc.setText("Danh mục");
        btnDanhMuc.setToolTipText("Danh mục");
        btnDanhMuc.setBorderPainted(false);
        btnDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhMucActionPerformed(evt);
            }
        });

        btnThucDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-restaurant-menu-24.png"))); // NOI18N
        btnThucDon.setText("Thực đơn");
        btnThucDon.setToolTipText("Thực đơn");
        btnThucDon.setBorderPainted(false);
        btnThucDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDanhMuc)
            .addComponent(btnThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnDanhMuc)
                .addGap(0, 0, 0)
                .addComponent(btnThucDon))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnNCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-supply-chain-24.png"))); // NOI18N
        btnNCC.setText("Nhà cung cấp");
        btnNCC.setToolTipText("Nhà cung cấp");
        btnNCC.setBorderPainted(false);
        btnNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });

        btnNguyenLieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNguyenLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-coffee-beans-24.png"))); // NOI18N
        btnNguyenLieu.setText("Nguyên liệu");
        btnNguyenLieu.setToolTipText("Nguyên liệu");
        btnNguyenLieu.setBorderPainted(false);
        btnNguyenLieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguyenLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNCC)
            .addComponent(btnNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnNCC)
                .addGap(0, 0, 0)
                .addComponent(btnNguyenLieu))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-male-user-24.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setToolTipText("Tài khoản");
        btnTaiKhoan.setBorderPainted(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTaiKhoan)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(204, 204, 204)));

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-account-24.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setToolTipText("Doanh thu");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(416, 416, 416)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(534, 534, 534)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(762, 762, 762)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnlManage.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnlManage, java.awt.BorderLayout.CENTER);

        tabPanelMain.addTab("Quản lý", jPanel2);

        mnTaiKhoan.setText("Tài khoản");
        mnTaiKhoan.setMaximumSize(new java.awt.Dimension(70, 32767));
        mnTaiKhoan.setMinimumSize(new java.awt.Dimension(70, 19));
        mnTaiKhoan.setPreferredSize(new java.awt.Dimension(70, 19));

        mnItemDangXuat.setText("Đăng xuất");
        mnItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDangXuatActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mnItemDangXuat);

        mnuItemInfoAcc.setText("Thông tin tài khoản");
        mnuItemInfoAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemInfoAccActionPerformed(evt);
            }
        });
        mnTaiKhoan.add(mnuItemInfoAcc);

        jMenuBar1.add(mnTaiKhoan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDangXuatActionPerformed
        this.dispose();
        new DangNhapGUI().setVisible(true);
    }//GEN-LAST:event_mnItemDangXuatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choosen = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
        if (choosen == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        pnlFeature.removeAll();
        pnlFeature.add(new OrderGUI(account));
        pnlFeature.repaint();
        pnlFeature.revalidate();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        pnlFeature.removeAll();
        pnlFeature.add(new MemberGUI(account));
        pnlFeature.repaint();
        pnlFeature.revalidate();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new NhanVienGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuVucActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new KhuVucGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnKhuVucActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new BanGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnBanActionPerformed

    private void btnDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhMucActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new DanhMucGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnDanhMucActionPerformed

    private void btnThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucDonActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new SanPhamGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnThucDonActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new TaiKhoanGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnCaLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaLamActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new CaLamGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnCaLamActionPerformed

    private void btnChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new ChamCongGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnChamCongActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new TinhLuongGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new NhaCungCapGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btnNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguyenLieuActionPerformed
        pnlManage.removeAll();
        pnlManage.add(new NguyenLieuGUI());
        pnlManage.repaint();
        pnlManage.revalidate();
    }//GEN-LAST:event_btnNguyenLieuActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        pnlFeature.removeAll();
        pnlFeature.add(new HoaDonGUI(account));
        pnlFeature.repaint();
        pnlFeature.revalidate();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        ThongKeGUI thongke = new ThongKeGUI(MainGUI.this, true);
        thongke.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        JOptionPane.showMessageDialog(null, "Comming soon :(", "Oops", JOptionPane.ERROR_MESSAGE, new ImageIcon(getClass().getResource("/error.png")));
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void mnuItemInfoAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemInfoAccActionPerformed
        txtTenDangNhap.setText(account.getTenDangNhap());
        txtTenHienThi.setText(account.getTenHienThi());
        txtMaNV.setText(account.getMaNV() + "");
        txtLoaiTK.setText(account.getIdLoaiTK() == 1 ? "Quản lý" : "Nhân viên");
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_mnuItemInfoAccActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnCaLam;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChamCong;
    private javax.swing.JButton btnDanhMuc;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhuVuc;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnNguyenLieu;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThucDon;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    protected javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem mnItemDangXuat;
    private javax.swing.JMenu mnTaiKhoan;
    private javax.swing.JMenuItem mnuItemInfoAcc;
    private javax.swing.JPanel pnlFeature;
    private javax.swing.JPanel pnlManage;
    private javax.swing.JTabbedPane tabPanelMain;
    protected javax.swing.JTextField txtLoaiTK;
    protected javax.swing.JTextField txtMaNV;
    protected javax.swing.JTextField txtTenDangNhap;
    protected javax.swing.JTextField txtTenHienThi;
    // End of variables declaration//GEN-END:variables

}
